[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zpui-example"
version = "0.1"
authors = [
  { name="Arya", email="arya@example.com" },
]
requires-python = ">=3.8"

[project.entry-points."zpui_app.3rdparty"]
zpui_example = "zpui_example:app"
